<?php

namespace Database\Seeders;

use App\Models\NominaCargo;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NominaCargoSeeder extends Seeder
{
    public function run()
    {
        NominaCargo::create([
            'item'=>'1',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'1',
            'escala_salarial_id'=>'1',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'2',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'2',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'3',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'3',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'4',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'4',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'5',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'5',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'6',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'6',
            'escala_salarial_id'=>'5',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'7',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'7',
            'escala_salarial_id'=>'6',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'8',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'8',
            'escala_salarial_id'=>'3',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'9',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'9',
            'escala_salarial_id'=>'6',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'10',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'10',
            'escala_salarial_id'=>'6',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'11',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'11',
            'escala_salarial_id'=>'5',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'12',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'12',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'13',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'13',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'14',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'1',
            'cargo_id'=>'14',
            'escala_salarial_id'=>'5',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'15',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'2',
            'cargo_id'=>'15',
            'escala_salarial_id'=>'2',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'16',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'2',
            'cargo_id'=>'16',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'17',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'2',
            'cargo_id'=>'17',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'18',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'2',
            'cargo_id'=>'18',
            'escala_salarial_id'=>'5',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'19',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'2',
            'cargo_id'=>'19',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'20',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'2',
            'cargo_id'=>'20',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'21',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'2',
            'cargo_id'=>'21',
            'escala_salarial_id'=>'7',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'22',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'3',
            'cargo_id'=>'22',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'23',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'3',
            'cargo_id'=>'23',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'24',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'3',
            'cargo_id'=>'24',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'25',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'3',
            'cargo_id'=>'25',
            'escala_salarial_id'=>'8',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'26',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'26',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'27',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'27',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'28',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'28',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'29',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'29',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'30',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'30',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'31',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'31',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'32',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'32',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'33',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'33',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'34',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'34',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'35',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'35',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'36',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'36',
            'escala_salarial_id'=>'9',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'37',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'37',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'38',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'38',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'39',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'39',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'40',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'40',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'41',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'41',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'42',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'42',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'43',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'43',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'44',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'44',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'45',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'45',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'46',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'46',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'47',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'47',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'48',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'48',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'49',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'49',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'50',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'50',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'51',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'51',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'52',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'4',
            'cargo_id'=>'52',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'53',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'5',
            'cargo_id'=>'53',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'54',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'5',
            'cargo_id'=>'54',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'55',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'5',
            'cargo_id'=>'55',
            'escala_salarial_id'=>'4',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'56',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'5',
            'cargo_id'=>'56',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'57',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'5',
            'cargo_id'=>'57',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'58',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'5',
            'cargo_id'=>'58',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'59',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'5',
            'cargo_id'=>'59',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'60',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'5',
            'cargo_id'=>'60',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'61',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'5',
            'cargo_id'=>'61',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'62',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'5',
            'cargo_id'=>'62',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'63',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'6',
            'cargo_id'=>'63',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'64',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'6',
            'cargo_id'=>'64',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'65',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'6',
            'cargo_id'=>'65',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'66',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'66',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'67',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'67',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'68',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'68',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'69',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'69',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'70',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'70',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'71',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'71',
            'escala_salarial_id'=>'7',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'72',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'72',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'73',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'73',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'74',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'74',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'75',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'75',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'76',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'76',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'77',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'77',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'78',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'78',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'79',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'79',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'80',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'80',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'81',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'81',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'82',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'82',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'83',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'83',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'84',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'84',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'85',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'85',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'86',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'86',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'87',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'87',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'88',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'88',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'89',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'89',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'90',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'90',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'91',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'91',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'92',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'92',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'93',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'93',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'94',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'94',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'95',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'95',
            'escala_salarial_id'=>'10',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'96',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'96',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'97',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'7',
            'cargo_id'=>'97',
            'escala_salarial_id'=>'10',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'98',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'8',
            'cargo_id'=>'98',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'99',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'8',
            'cargo_id'=>'99',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'100',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'8',
            'cargo_id'=>'100',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'101',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'8',
            'cargo_id'=>'101',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'102',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'8',
            'cargo_id'=>'102',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'103',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'8',
            'cargo_id'=>'103',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'104',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'8',
            'cargo_id'=>'104',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'105',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'8',
            'cargo_id'=>'105',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'106',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'106',
            'escala_salarial_id'=>'3',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'107',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'107',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'108',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'108',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'109',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'109',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'110',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'110',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'111',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'111',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'112',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'112',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'113',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'113',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'114',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'114',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'115',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'115',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'116',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'116',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'117',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'117',
            'escala_salarial_id'=>'10',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'118',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'118',
            'escala_salarial_id'=>'10',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'119',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'119',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'120',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'120',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'121',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'121',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'122',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'122',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'123',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'123',
            'escala_salarial_id'=>'10',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'124',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'124',
            'escala_salarial_id'=>'10',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'125',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'9',
            'cargo_id'=>'125',
            'escala_salarial_id'=>'10',
            'estado'=>'LIBRE',
        ]);

        NominaCargo::create([
            'item'=>'126',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'10',
            'cargo_id'=>'126',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'127',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'10',
            'cargo_id'=>'127',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'128',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'10',
            'cargo_id'=>'128',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'129',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'10',
            'cargo_id'=>'129',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'130',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'10',
            'cargo_id'=>'130',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'131',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'10',
            'cargo_id'=>'131',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'132',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'10',
            'cargo_id'=>'132',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'133',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'10',
            'cargo_id'=>'133',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'134',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'10',
            'cargo_id'=>'134',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'135',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'10',
            'cargo_id'=>'135',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);

        NominaCargo::create([
            'item'=>'136',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'136',
            'escala_salarial_id'=>'2',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'137',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'137',
            'escala_salarial_id'=>'7',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'138',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'138',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'139',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'139',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'140',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'140',
            'escala_salarial_id'=>'4',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'141',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'141',
            'escala_salarial_id'=>'5',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'142',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'142',
            'escala_salarial_id'=>'5',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'143',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'143',
            'escala_salarial_id'=>'5',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'144',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'144',
            'escala_salarial_id'=>'6',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'145',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'145',
            'escala_salarial_id'=>'6',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'146',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'146',
            'escala_salarial_id'=>'6',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'147',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'147',
            'escala_salarial_id'=>'6',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'148',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'148',
            'escala_salarial_id'=>'6',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'149',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'149',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'150',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'150',
            'escala_salarial_id'=>'6',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'151',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'151',
            'escala_salarial_id'=>'6',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'152',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'152',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'153',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'153',
            'escala_salarial_id'=>'5',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'154',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'154',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'155',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'155',
            'escala_salarial_id'=>'5',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'156',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'156',
            'escala_salarial_id'=>'5',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'157',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'157',
            'escala_salarial_id'=>'8',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'158',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'158',
            'escala_salarial_id'=>'9',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'159',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'159',
            'escala_salarial_id'=>'9',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'160',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'160',
            'escala_salarial_id'=>'9',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'161',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'161',
            'escala_salarial_id'=>'9',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'162',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'11',
            'cargo_id'=>'162',
            'escala_salarial_id'=>'9',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'163',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'163',
            'escala_salarial_id'=>'2',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'164',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'164',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'165',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'165',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'166',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'166',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'167',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'167',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'168',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'168',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'169',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'169',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'170',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'170',
            'escala_salarial_id'=>'6',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'171',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'171',
            'escala_salarial_id'=>'6',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'172',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'172',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'173',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'173',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'174',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'174',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'175',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'175',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'176',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'176',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'177',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'177',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'178',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'178',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'179',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'179',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'180',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'180',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'181',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'181',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'182',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'182',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'183',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'183',
            'escala_salarial_id'=>'8',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'184',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'184',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'185',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'185',
            'escala_salarial_id'=>'3',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'186',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'186',
            'escala_salarial_id'=>'5',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'187',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'187',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'188',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'188',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'189',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'189',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'190',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'190',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'191',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'191',
            'escala_salarial_id'=>'6',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'192',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'192',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'193',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'193',
            'escala_salarial_id'=>'8',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'194',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'194',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'195',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'195',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'196',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'196',
            'escala_salarial_id'=>'7',
            'estado'=>'OCUPADO',
        ]);
        NominaCargo::create([
            'item'=>'197',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'197',
            'escala_salarial_id'=>'8',
            'estado'=>'LIBRE',
        ]);
        NominaCargo::create([
            'item'=>'198',
            'tipo_contrato_id'=>'1',
            'unidad_organizacional_id'=>'12',
            'cargo_id'=>'198',
            'escala_salarial_id'=>'10',
            'estado'=>'LIBRE',
        ]);
    }
}
