<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class NominaCargosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('nomina_cargos')->delete();
        
        \DB::table('nomina_cargos')->insert(array (
            0 => 
            array (
                'item' => 1,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 1,
                'escala_salarial_id' => 1,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            1 => 
            array (
                'item' => 2,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 2,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            2 => 
            array (
                'item' => 3,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 3,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            3 => 
            array (
                'item' => 4,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 4,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            4 => 
            array (
                'item' => 5,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 5,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            5 => 
            array (
                'item' => 6,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 6,
                'escala_salarial_id' => 5,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            6 => 
            array (
                'item' => 7,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 7,
                'escala_salarial_id' => 6,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            7 => 
            array (
                'item' => 8,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 8,
                'escala_salarial_id' => 3,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            8 => 
            array (
                'item' => 9,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 9,
                'escala_salarial_id' => 6,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            9 => 
            array (
                'item' => 10,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 10,
                'escala_salarial_id' => 6,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            10 => 
            array (
                'item' => 11,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 11,
                'escala_salarial_id' => 5,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            11 => 
            array (
                'item' => 12,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 12,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            12 => 
            array (
                'item' => 13,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 13,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            13 => 
            array (
                'item' => 14,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 1,
                'cargo_id' => 14,
                'escala_salarial_id' => 5,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            14 => 
            array (
                'item' => 15,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 2,
                'cargo_id' => 15,
                'escala_salarial_id' => 2,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            15 => 
            array (
                'item' => 16,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 2,
                'cargo_id' => 16,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            16 => 
            array (
                'item' => 17,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 2,
                'cargo_id' => 17,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            17 => 
            array (
                'item' => 18,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 2,
                'cargo_id' => 18,
                'escala_salarial_id' => 5,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            18 => 
            array (
                'item' => 19,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 2,
                'cargo_id' => 19,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            19 => 
            array (
                'item' => 20,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 2,
                'cargo_id' => 20,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            20 => 
            array (
                'item' => 21,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 2,
                'cargo_id' => 21,
                'escala_salarial_id' => 7,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            21 => 
            array (
                'item' => 22,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 3,
                'cargo_id' => 22,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            22 => 
            array (
                'item' => 23,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 3,
                'cargo_id' => 23,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            23 => 
            array (
                'item' => 24,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 3,
                'cargo_id' => 24,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            24 => 
            array (
                'item' => 25,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 3,
                'cargo_id' => 25,
                'escala_salarial_id' => 8,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            25 => 
            array (
                'item' => 26,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 26,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            26 => 
            array (
                'item' => 27,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 27,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            27 => 
            array (
                'item' => 28,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 28,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            28 => 
            array (
                'item' => 29,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 29,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            29 => 
            array (
                'item' => 30,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 30,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            30 => 
            array (
                'item' => 31,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 31,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            31 => 
            array (
                'item' => 32,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 32,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            32 => 
            array (
                'item' => 33,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 33,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            33 => 
            array (
                'item' => 34,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 34,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            34 => 
            array (
                'item' => 35,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 35,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            35 => 
            array (
                'item' => 36,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 36,
                'escala_salarial_id' => 9,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            36 => 
            array (
                'item' => 37,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 37,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            37 => 
            array (
                'item' => 38,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 38,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            38 => 
            array (
                'item' => 39,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 39,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            39 => 
            array (
                'item' => 40,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 40,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            40 => 
            array (
                'item' => 41,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 41,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            41 => 
            array (
                'item' => 42,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 42,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            42 => 
            array (
                'item' => 43,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 43,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            43 => 
            array (
                'item' => 44,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 44,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            44 => 
            array (
                'item' => 45,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 45,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            45 => 
            array (
                'item' => 46,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 46,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            46 => 
            array (
                'item' => 47,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 47,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            47 => 
            array (
                'item' => 48,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 48,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            48 => 
            array (
                'item' => 49,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 49,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            49 => 
            array (
                'item' => 50,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 50,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            50 => 
            array (
                'item' => 51,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 51,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            51 => 
            array (
                'item' => 52,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 4,
                'cargo_id' => 52,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            52 => 
            array (
                'item' => 53,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 5,
                'cargo_id' => 53,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            53 => 
            array (
                'item' => 54,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 5,
                'cargo_id' => 54,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            54 => 
            array (
                'item' => 55,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 5,
                'cargo_id' => 55,
                'escala_salarial_id' => 4,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            55 => 
            array (
                'item' => 56,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 5,
                'cargo_id' => 56,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            56 => 
            array (
                'item' => 57,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 5,
                'cargo_id' => 57,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            57 => 
            array (
                'item' => 58,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 5,
                'cargo_id' => 58,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            58 => 
            array (
                'item' => 59,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 5,
                'cargo_id' => 59,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            59 => 
            array (
                'item' => 60,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 5,
                'cargo_id' => 60,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            60 => 
            array (
                'item' => 61,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 5,
                'cargo_id' => 61,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            61 => 
            array (
                'item' => 62,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 5,
                'cargo_id' => 62,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            62 => 
            array (
                'item' => 63,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 6,
                'cargo_id' => 63,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            63 => 
            array (
                'item' => 64,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 6,
                'cargo_id' => 64,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            64 => 
            array (
                'item' => 65,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 6,
                'cargo_id' => 65,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            65 => 
            array (
                'item' => 66,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 66,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            66 => 
            array (
                'item' => 67,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 67,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            67 => 
            array (
                'item' => 68,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 68,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            68 => 
            array (
                'item' => 69,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 69,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            69 => 
            array (
                'item' => 70,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 70,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            70 => 
            array (
                'item' => 71,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 71,
                'escala_salarial_id' => 7,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            71 => 
            array (
                'item' => 72,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 72,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            72 => 
            array (
                'item' => 73,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 73,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            73 => 
            array (
                'item' => 74,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 74,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            74 => 
            array (
                'item' => 75,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 75,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            75 => 
            array (
                'item' => 76,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 76,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            76 => 
            array (
                'item' => 77,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 77,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            77 => 
            array (
                'item' => 78,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 78,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            78 => 
            array (
                'item' => 79,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 79,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            79 => 
            array (
                'item' => 80,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 80,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            80 => 
            array (
                'item' => 81,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 81,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            81 => 
            array (
                'item' => 82,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 82,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            82 => 
            array (
                'item' => 83,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 83,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            83 => 
            array (
                'item' => 84,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 84,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            84 => 
            array (
                'item' => 85,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 85,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            85 => 
            array (
                'item' => 86,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 86,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            86 => 
            array (
                'item' => 87,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 87,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            87 => 
            array (
                'item' => 88,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 88,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            88 => 
            array (
                'item' => 89,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 89,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            89 => 
            array (
                'item' => 90,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 90,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            90 => 
            array (
                'item' => 91,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 91,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            91 => 
            array (
                'item' => 92,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 92,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            92 => 
            array (
                'item' => 93,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 93,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            93 => 
            array (
                'item' => 94,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 94,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            94 => 
            array (
                'item' => 95,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 95,
                'escala_salarial_id' => 10,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            95 => 
            array (
                'item' => 96,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 96,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            96 => 
            array (
                'item' => 97,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 7,
                'cargo_id' => 97,
                'escala_salarial_id' => 10,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            97 => 
            array (
                'item' => 98,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 8,
                'cargo_id' => 98,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            98 => 
            array (
                'item' => 99,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 8,
                'cargo_id' => 99,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            99 => 
            array (
                'item' => 100,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 8,
                'cargo_id' => 100,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            100 => 
            array (
                'item' => 101,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 8,
                'cargo_id' => 101,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            101 => 
            array (
                'item' => 102,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 8,
                'cargo_id' => 102,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            102 => 
            array (
                'item' => 103,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 8,
                'cargo_id' => 103,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            103 => 
            array (
                'item' => 104,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 8,
                'cargo_id' => 104,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            104 => 
            array (
                'item' => 105,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 8,
                'cargo_id' => 105,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            105 => 
            array (
                'item' => 106,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 106,
                'escala_salarial_id' => 3,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            106 => 
            array (
                'item' => 107,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 107,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            107 => 
            array (
                'item' => 108,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 108,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            108 => 
            array (
                'item' => 109,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 109,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            109 => 
            array (
                'item' => 110,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 110,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            110 => 
            array (
                'item' => 111,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 111,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            111 => 
            array (
                'item' => 112,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 112,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            112 => 
            array (
                'item' => 113,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 113,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            113 => 
            array (
                'item' => 114,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 114,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            114 => 
            array (
                'item' => 115,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 115,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            115 => 
            array (
                'item' => 116,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 116,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            116 => 
            array (
                'item' => 118,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 118,
                'escala_salarial_id' => 10,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            117 => 
            array (
                'item' => 119,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 119,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            118 => 
            array (
                'item' => 120,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 120,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            119 => 
            array (
                'item' => 121,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 121,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            120 => 
            array (
                'item' => 122,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 122,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            121 => 
            array (
                'item' => 124,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 124,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            122 => 
            array (
                'item' => 125,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 125,
                'escala_salarial_id' => 10,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            123 => 
            array (
                'item' => 126,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 10,
                'cargo_id' => 126,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            124 => 
            array (
                'item' => 127,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 10,
                'cargo_id' => 127,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            125 => 
            array (
                'item' => 128,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 10,
                'cargo_id' => 128,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            126 => 
            array (
                'item' => 129,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 10,
                'cargo_id' => 129,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            127 => 
            array (
                'item' => 130,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 10,
                'cargo_id' => 130,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            128 => 
            array (
                'item' => 131,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 10,
                'cargo_id' => 131,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            129 => 
            array (
                'item' => 132,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 10,
                'cargo_id' => 132,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            130 => 
            array (
                'item' => 133,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 10,
                'cargo_id' => 133,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            131 => 
            array (
                'item' => 134,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 10,
                'cargo_id' => 134,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            132 => 
            array (
                'item' => 135,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 10,
                'cargo_id' => 135,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            133 => 
            array (
                'item' => 136,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 136,
                'escala_salarial_id' => 2,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            134 => 
            array (
                'item' => 137,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 137,
                'escala_salarial_id' => 7,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            135 => 
            array (
                'item' => 138,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 138,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            136 => 
            array (
                'item' => 139,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 139,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            137 => 
            array (
                'item' => 140,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 140,
                'escala_salarial_id' => 4,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            138 => 
            array (
                'item' => 141,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 141,
                'escala_salarial_id' => 5,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            139 => 
            array (
                'item' => 142,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 142,
                'escala_salarial_id' => 5,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            140 => 
            array (
                'item' => 143,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 143,
                'escala_salarial_id' => 5,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            141 => 
            array (
                'item' => 144,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 144,
                'escala_salarial_id' => 6,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            142 => 
            array (
                'item' => 145,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 145,
                'escala_salarial_id' => 6,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            143 => 
            array (
                'item' => 146,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 146,
                'escala_salarial_id' => 6,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            144 => 
            array (
                'item' => 147,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 147,
                'escala_salarial_id' => 6,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            145 => 
            array (
                'item' => 148,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 148,
                'escala_salarial_id' => 6,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            146 => 
            array (
                'item' => 149,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 149,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            147 => 
            array (
                'item' => 150,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 150,
                'escala_salarial_id' => 6,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            148 => 
            array (
                'item' => 151,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 151,
                'escala_salarial_id' => 6,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            149 => 
            array (
                'item' => 152,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 152,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            150 => 
            array (
                'item' => 153,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 153,
                'escala_salarial_id' => 5,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            151 => 
            array (
                'item' => 154,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 154,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            152 => 
            array (
                'item' => 155,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 155,
                'escala_salarial_id' => 5,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            153 => 
            array (
                'item' => 156,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 156,
                'escala_salarial_id' => 5,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            154 => 
            array (
                'item' => 157,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 157,
                'escala_salarial_id' => 8,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            155 => 
            array (
                'item' => 158,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 158,
                'escala_salarial_id' => 9,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            156 => 
            array (
                'item' => 159,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 159,
                'escala_salarial_id' => 9,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            157 => 
            array (
                'item' => 160,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 160,
                'escala_salarial_id' => 9,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            158 => 
            array (
                'item' => 161,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 161,
                'escala_salarial_id' => 9,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            159 => 
            array (
                'item' => 162,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 11,
                'cargo_id' => 162,
                'escala_salarial_id' => 9,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            160 => 
            array (
                'item' => 123,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 123,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            161 => 
            array (
                'item' => 163,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 163,
                'escala_salarial_id' => 2,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            162 => 
            array (
                'item' => 164,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 164,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            163 => 
            array (
                'item' => 165,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 165,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            164 => 
            array (
                'item' => 166,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 166,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            165 => 
            array (
                'item' => 167,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 167,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            166 => 
            array (
                'item' => 168,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 168,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            167 => 
            array (
                'item' => 169,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 169,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            168 => 
            array (
                'item' => 170,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 170,
                'escala_salarial_id' => 6,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            169 => 
            array (
                'item' => 171,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 171,
                'escala_salarial_id' => 6,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            170 => 
            array (
                'item' => 172,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 172,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            171 => 
            array (
                'item' => 173,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 173,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            172 => 
            array (
                'item' => 174,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 174,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            173 => 
            array (
                'item' => 175,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 175,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            174 => 
            array (
                'item' => 176,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 176,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            175 => 
            array (
                'item' => 177,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 177,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            176 => 
            array (
                'item' => 178,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 178,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            177 => 
            array (
                'item' => 179,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 179,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            178 => 
            array (
                'item' => 180,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 180,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            179 => 
            array (
                'item' => 181,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 181,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            180 => 
            array (
                'item' => 182,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 182,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            181 => 
            array (
                'item' => 183,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 183,
                'escala_salarial_id' => 8,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            182 => 
            array (
                'item' => 184,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 184,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            183 => 
            array (
                'item' => 185,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 185,
                'escala_salarial_id' => 3,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            184 => 
            array (
                'item' => 186,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 186,
                'escala_salarial_id' => 5,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            185 => 
            array (
                'item' => 187,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 187,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            186 => 
            array (
                'item' => 188,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 188,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            187 => 
            array (
                'item' => 189,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 189,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            188 => 
            array (
                'item' => 190,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 190,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            189 => 
            array (
                'item' => 191,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 191,
                'escala_salarial_id' => 6,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            190 => 
            array (
                'item' => 192,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 192,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            191 => 
            array (
                'item' => 193,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 193,
                'escala_salarial_id' => 8,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            192 => 
            array (
                'item' => 194,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 194,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            193 => 
            array (
                'item' => 195,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 195,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            194 => 
            array (
                'item' => 196,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 196,
                'escala_salarial_id' => 7,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            195 => 
            array (
                'item' => 197,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 197,
                'escala_salarial_id' => 8,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            196 => 
            array (
                'item' => 198,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 12,
                'cargo_id' => 198,
                'escala_salarial_id' => 10,
                'estado' => 'LIBRE',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:21:15',
            ),
            197 => 
            array (
                'item' => 117,
                'tipo_contrato_id' => 1,
                'unidad_organizacional_id' => 9,
                'cargo_id' => 117,
                'escala_salarial_id' => 10,
                'estado' => 'OCUPADO',
                'created_at' => '2022-08-29 14:21:15',
                'updated_at' => '2022-08-29 14:43:14',
            ),
        ));
        
        
    }
}