<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PlanillaSuplenciasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('planilla_suplencias')->delete();
        
        \DB::table('planilla_suplencias')->insert(array (
            0 => 
            array (
                'mes' => 1,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-01-01',
                'fecha_fin' => '2022-01-06',
                'total_dias' => '6.00',
                'salario_mensual' => '14134.00',
                'monto' => '543.80',
                'cargo_suplencia' => 'Gerente Administrativo y Financiero',
                'motivo' => NULL,
                'asignacion_cargo_id' => 167,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'mes' => 1,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-01-01',
                'fecha_fin' => '2022-01-31',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '1595.00',
                'cargo_suplencia' => 'Secretaria Gerencia Adm. y Financiero',
                'motivo' => NULL,
                'asignacion_cargo_id' => 86,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'mes' => 1,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-01-03',
                'fecha_fin' => '2022-01-31',
                'total_dias' => '28.00',
                'salario_mensual' => '8547.00',
                'monto' => '1237.60',
                'cargo_suplencia' => 'Responsable de Cortes',
                'motivo' => NULL,
                'asignacion_cargo_id' => 133,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'mes' => 1,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-01-01',
                'fecha_fin' => '2022-01-31',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '1262.00',
                'cargo_suplencia' => 'Capataz Socapampa',
                'motivo' => NULL,
                'asignacion_cargo_id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'mes' => 1,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-01-01',
                'fecha_fin' => '2022-01-13',
                'total_dias' => '13.00',
                'salario_mensual' => '7221.00',
                'monto' => '383.07',
                'cargo_suplencia' => 'Catastro de Usuarios',
                'motivo' => NULL,
                'asignacion_cargo_id' => 173,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'mes' => 1,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-01-07',
                'fecha_fin' => '2022-01-31',
                'total_dias' => '24.00',
                'salario_mensual' => '11415.00',
                'monto' => '1376.00',
                'cargo_suplencia' => 'Jefe de Planificacion y Proyectos',
                'motivo' => NULL,
                'asignacion_cargo_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'mes' => 1,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-01-03',
                'fecha_fin' => '2022-01-31',
                'total_dias' => '28.00',
                'salario_mensual' => '11415.00',
                'monto' => '3914.40',
                'cargo_suplencia' => 'Asesor Juridico',
                'motivo' => NULL,
                'asignacion_cargo_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'mes' => 1,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-01-01',
                'fecha_fin' => '2022-01-31',
                'total_dias' => '30.00',
                'salario_mensual' => '11415.00',
                'monto' => '1720.00',
                'cargo_suplencia' => 'Jefe Red de Alcantarillado',
                'motivo' => NULL,
                'asignacion_cargo_id' => 212,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'mes' => 2,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-02-01',
                'fecha_fin' => '2022-02-06',
                'total_dias' => '6.00',
                'salario_mensual' => '6337.00',
                'monto' => '319.00',
                'cargo_suplencia' => 'Secretaria Gerencia Adm. y Financiero',
                'motivo' => NULL,
                'asignacion_cargo_id' => 86,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'mes' => 2,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-02-01',
                'fecha_fin' => '2022-02-28',
                'total_dias' => '30.00',
                'salario_mensual' => '8547.00',
                'monto' => '1326.00',
                'cargo_suplencia' => 'Responsable de Cortes',
                'motivo' => NULL,
                'asignacion_cargo_id' => 133,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'mes' => 2,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-02-01',
                'fecha_fin' => '2022-02-28',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '1262.00',
                'cargo_suplencia' => 'Capataz Socapampa',
                'motivo' => NULL,
                'asignacion_cargo_id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'mes' => 2,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-02-07',
                'fecha_fin' => '2022-02-28',
                'total_dias' => '22.00',
                'salario_mensual' => '6337.00',
                'monto' => '1169.67',
                'cargo_suplencia' => 'Secretaria Gerencia Tecnica',
                'motivo' => NULL,
                'asignacion_cargo_id' => 83,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'mes' => 2,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-02-01',
                'fecha_fin' => '2022-02-28',
                'total_dias' => '30.00',
                'salario_mensual' => '11415.00',
                'monto' => '1720.00',
                'cargo_suplencia' => 'Jefe Red de Alcantarillado',
                'motivo' => NULL,
                'asignacion_cargo_id' => 212,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'mes' => 2,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-02-04',
                'fecha_fin' => '2022-02-28',
                'total_dias' => '25.00',
                'salario_mensual' => '6337.00',
                'monto' => '1051.67',
                'cargo_suplencia' => 'Capataz Ruffo',
                'motivo' => NULL,
                'asignacion_cargo_id' => 215,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'mes' => 2,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-02-01',
                'fecha_fin' => '2022-02-04',
                'total_dias' => '4.00',
                'salario_mensual' => '11415.00',
                'monto' => '229.33',
                'cargo_suplencia' => 'Jefe de Planificacion y Proyectos',
                'motivo' => NULL,
                'asignacion_cargo_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'mes' => 2,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-02-01',
                'fecha_fin' => '2022-02-28',
                'total_dias' => '30.00',
                'salario_mensual' => '11415.00',
                'monto' => '4194.00',
                'cargo_suplencia' => 'Asesor Juridico',
                'motivo' => NULL,
                'asignacion_cargo_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'mes' => 3,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-03-09',
                'fecha_fin' => '2022-03-31',
                'total_dias' => '22.00',
                'salario_mensual' => '17827.00',
                'monto' => '2708.20',
                'cargo_suplencia' => 'Gerente General',
                'motivo' => NULL,
                'asignacion_cargo_id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'mes' => 3,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-03-01',
                'fecha_fin' => '2022-03-31',
                'total_dias' => '30.00',
                'salario_mensual' => '11415.00',
                'monto' => '4194.00',
                'cargo_suplencia' => 'Asesor Juridico',
                'motivo' => NULL,
                'asignacion_cargo_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'mes' => 3,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-03-01',
                'fecha_fin' => '2022-03-20',
                'total_dias' => '20.00',
                'salario_mensual' => '8547.00',
                'monto' => '884.00',
                'cargo_suplencia' => 'Responsable de Cortes',
                'motivo' => NULL,
                'asignacion_cargo_id' => 133,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'mes' => 3,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-03-01',
                'fecha_fin' => '2022-03-31',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '1262.00',
                'cargo_suplencia' => 'Capataz Socapampa',
                'motivo' => NULL,
                'asignacion_cargo_id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'mes' => 3,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-03-01',
                'fecha_fin' => '2022-03-04',
                'total_dias' => '4.00',
                'salario_mensual' => '6337.00',
                'monto' => '212.67',
                'cargo_suplencia' => 'Secretaria Gerencia Tecnica',
                'motivo' => NULL,
                'asignacion_cargo_id' => 83,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'mes' => 3,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-03-01',
                'fecha_fin' => '2022-03-07',
                'total_dias' => '7.00',
                'salario_mensual' => '11415.00',
                'monto' => '401.33',
                'cargo_suplencia' => 'Jefe Red de Alcantarillado',
                'motivo' => NULL,
                'asignacion_cargo_id' => 212,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'mes' => 3,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-03-01',
                'fecha_fin' => '2022-03-21',
                'total_dias' => '21.00',
                'salario_mensual' => '6337.00',
                'monto' => '883.40',
                'cargo_suplencia' => 'Capataz Ruffo',
                'motivo' => NULL,
                'asignacion_cargo_id' => 215,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'mes' => 3,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-03-02',
                'fecha_fin' => '2022-03-31',
                'total_dias' => '29.00',
                'salario_mensual' => '6337.00',
                'monto' => '681.50',
                'cargo_suplencia' => 'Inspector de Reclamos',
                'motivo' => NULL,
                'asignacion_cargo_id' => 161,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'mes' => 3,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-03-02',
                'fecha_fin' => '2022-03-31',
                'total_dias' => '29.00',
                'salario_mensual' => '7221.00',
                'monto' => '854.53',
                'cargo_suplencia' => 'Responsable de Lecturas',
                'motivo' => NULL,
                'asignacion_cargo_id' => 233,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'mes' => 4,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-04-01',
                'fecha_fin' => '2022-04-30',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '1262.00',
                'cargo_suplencia' => 'Capataz Socapampa',
                'motivo' => NULL,
                'asignacion_cargo_id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'mes' => 4,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-04-01',
                'fecha_fin' => '2022-04-30',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '705.00',
                'cargo_suplencia' => 'Inspector de Reclamos',
                'motivo' => NULL,
                'asignacion_cargo_id' => 161,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'mes' => 4,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-04-01',
                'fecha_fin' => '2022-04-11',
                'total_dias' => '11.00',
                'salario_mensual' => '7221.00',
                'monto' => '324.13',
                'cargo_suplencia' => 'Responsable de Lecturas',
                'motivo' => NULL,
                'asignacion_cargo_id' => 233,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'mes' => 4,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-04-01',
                'fecha_fin' => '2022-04-30',
                'total_dias' => '30.00',
                'salario_mensual' => '17827.00',
                'monto' => '3693.00',
                'cargo_suplencia' => 'Gerente General',
                'motivo' => NULL,
                'asignacion_cargo_id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'mes' => 4,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-04-01',
                'fecha_fin' => '2022-04-30',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '1595.00',
                'cargo_suplencia' => 'Secretaria Gerencia Adm. y Financiero',
                'motivo' => NULL,
                'asignacion_cargo_id' => 86,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'mes' => 4,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-04-01',
                'fecha_fin' => '2022-04-30',
                'total_dias' => '30.00',
                'salario_mensual' => '8547.00',
                'monto' => '1326.00',
                'cargo_suplencia' => 'Responsable de Cortes',
                'motivo' => NULL,
                'asignacion_cargo_id' => 134,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'mes' => 4,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-04-01',
                'fecha_fin' => '2022-04-30',
                'total_dias' => '30.00',
                'salario_mensual' => '7221.00',
                'monto' => '2479.00',
                'cargo_suplencia' => 'Cajero',
                'motivo' => NULL,
                'asignacion_cargo_id' => 83,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'mes' => 4,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-04-01',
                'fecha_fin' => '2022-04-30',
                'total_dias' => '30.00',
                'salario_mensual' => '11415.00',
                'monto' => '1720.00',
                'cargo_suplencia' => 'Jefe Control de Calidad',
                'motivo' => NULL,
                'asignacion_cargo_id' => 57,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'mes' => 5,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-05-01',
                'fecha_fin' => '2022-05-31',
                'total_dias' => '30.00',
                'salario_mensual' => '17827.00',
                'monto' => '3693.00',
                'cargo_suplencia' => 'Gerente General',
                'motivo' => NULL,
                'asignacion_cargo_id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'mes' => 5,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-05-01',
                'fecha_fin' => '2022-05-31',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '1262.00',
                'cargo_suplencia' => 'Capataz Socapampa',
                'motivo' => NULL,
                'asignacion_cargo_id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'mes' => 5,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-05-01',
                'fecha_fin' => '2022-05-31',
                'total_dias' => '30.00',
                'salario_mensual' => '7221.00',
                'monto' => '2479.00',
                'cargo_suplencia' => 'Cajero',
                'motivo' => NULL,
                'asignacion_cargo_id' => 83,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'mes' => 5,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-05-01',
                'fecha_fin' => '2022-05-09',
                'total_dias' => '9.00',
                'salario_mensual' => '11415.00',
                'monto' => '516.00',
                'cargo_suplencia' => 'Jefe Control de Calidad',
                'motivo' => NULL,
                'asignacion_cargo_id' => 57,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'mes' => 5,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-05-01',
                'fecha_fin' => '2022-05-31',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '1595.00',
                'cargo_suplencia' => 'Secretaria Gerencia Adm. y Financiero',
                'motivo' => NULL,
                'asignacion_cargo_id' => 86,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'mes' => 5,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-05-01',
                'fecha_fin' => '2022-05-31',
                'total_dias' => '30.00',
                'salario_mensual' => '8547.00',
                'monto' => '1326.00',
                'cargo_suplencia' => 'Responsable de Cortes',
                'motivo' => NULL,
                'asignacion_cargo_id' => 134,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'mes' => 5,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-05-01',
                'fecha_fin' => '2022-05-31',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '705.00',
                'cargo_suplencia' => 'Inspector de Reclamos',
                'motivo' => NULL,
                'asignacion_cargo_id' => 161,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'mes' => 5,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-05-01',
                'fecha_fin' => '2022-05-16',
                'total_dias' => '16.00',
                'salario_mensual' => '7221.00',
                'monto' => '471.47',
                'cargo_suplencia' => 'Secretaria Gerencia General',
                'motivo' => NULL,
                'asignacion_cargo_id' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'mes' => 5,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-05-01',
                'fecha_fin' => '2022-05-17',
                'total_dias' => '17.00',
                'salario_mensual' => '6337.00',
                'monto' => '903.83',
                'cargo_suplencia' => 'Inspector Red de Agua',
                'motivo' => NULL,
                'asignacion_cargo_id' => 95,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'mes' => 5,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-05-11',
                'fecha_fin' => '2022-05-31',
                'total_dias' => '20.00',
                'salario_mensual' => '14134.00',
                'monto' => '1812.67',
                'cargo_suplencia' => 'Gerente Tecnico',
                'motivo' => NULL,
                'asignacion_cargo_id' => 59,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'mes' => 6,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-06-01',
                'fecha_fin' => '2022-06-30',
                'total_dias' => '30.00',
                'salario_mensual' => '17827.00',
                'monto' => '3693.00',
                'cargo_suplencia' => 'Gerente General',
                'motivo' => NULL,
                'asignacion_cargo_id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'mes' => 6,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-06-20',
                'fecha_fin' => '2022-06-30',
                'total_dias' => '11.00',
                'salario_mensual' => '11415.00',
                'monto' => '630.67',
                'cargo_suplencia' => 'Jefe Captacion y Aduccion',
                'motivo' => NULL,
                'asignacion_cargo_id' => 212,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'mes' => 6,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-06-08',
                'fecha_fin' => '2022-06-30',
                'total_dias' => '23.00',
                'salario_mensual' => '5075.00',
                'monto' => '255.30',
                'cargo_suplencia' => 'Operador Planta Potabilizadora',
                'motivo' => NULL,
                'asignacion_cargo_id' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'mes' => 6,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-06-01',
                'fecha_fin' => '2022-06-30',
                'total_dias' => '30.00',
                'salario_mensual' => '14134.00',
                'monto' => '2719.00',
                'cargo_suplencia' => 'Gerente Tecnico',
                'motivo' => NULL,
                'asignacion_cargo_id' => 59,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'mes' => 6,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-06-01',
                'fecha_fin' => '2022-06-10',
                'total_dias' => '10.00',
                'salario_mensual' => '7221.00',
                'monto' => '826.33',
                'cargo_suplencia' => 'Cajero',
                'motivo' => NULL,
                'asignacion_cargo_id' => 83,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'mes' => 6,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-06-01',
                'fecha_fin' => '2022-06-10',
                'total_dias' => '10.00',
                'salario_mensual' => '6337.00',
                'monto' => '531.67',
                'cargo_suplencia' => 'Secretaria Gerencia Adm. y Financiero',
                'motivo' => NULL,
                'asignacion_cargo_id' => 86,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'mes' => 6,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-06-01',
                'fecha_fin' => '2022-06-30',
                'total_dias' => '30.00',
                'salario_mensual' => '8547.00',
                'monto' => '1326.00',
                'cargo_suplencia' => 'Responsable de Cortes',
                'motivo' => NULL,
                'asignacion_cargo_id' => 134,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'mes' => 6,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-06-06',
                'fecha_fin' => '2022-06-30',
                'total_dias' => '25.00',
                'salario_mensual' => '7221.00',
                'monto' => '736.67',
                'cargo_suplencia' => 'Responsable de Lecturas',
                'motivo' => NULL,
                'asignacion_cargo_id' => 233,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'mes' => 6,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-06-01',
                'fecha_fin' => '2022-06-30',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '705.00',
                'cargo_suplencia' => 'Inspector de Reclamos',
                'motivo' => NULL,
                'asignacion_cargo_id' => 161,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-01',
                'fecha_fin' => '2022-07-31',
                'total_dias' => '30.00',
                'salario_mensual' => '17827.00',
                'monto' => '3693.00',
                'cargo_suplencia' => 'Gerente General',
                'motivo' => NULL,
                'asignacion_cargo_id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-01',
                'fecha_fin' => '2022-07-31',
                'total_dias' => '30.00',
                'salario_mensual' => '11415.00',
                'monto' => '1720.00',
                'cargo_suplencia' => 'Jefe Captacion y Aduccion',
                'motivo' => NULL,
                'asignacion_cargo_id' => 212,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-01',
                'fecha_fin' => '2022-07-15',
                'total_dias' => '15.00',
                'salario_mensual' => '5075.00',
                'monto' => '166.50',
                'cargo_suplencia' => 'Operador Planta Potabilizadora',
                'motivo' => NULL,
                'asignacion_cargo_id' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-20',
                'fecha_fin' => '2022-07-30',
                'total_dias' => '11.00',
                'salario_mensual' => '5075.00',
                'monto' => '122.10',
                'cargo_suplencia' => 'Operador Planta Potabilizadora',
                'motivo' => NULL,
                'asignacion_cargo_id' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-01',
                'fecha_fin' => '2022-07-31',
                'total_dias' => '30.00',
                'salario_mensual' => '14134.00',
                'monto' => '2719.00',
                'cargo_suplencia' => 'Gerente Tecnico',
                'motivo' => NULL,
                'asignacion_cargo_id' => 59,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-01',
                'fecha_fin' => '2022-07-27',
                'total_dias' => '27.00',
                'salario_mensual' => '6337.00',
                'monto' => '634.50',
                'cargo_suplencia' => 'Inspector de Reclamos',
                'motivo' => NULL,
                'asignacion_cargo_id' => 161,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-06',
                'fecha_fin' => '2022-07-30',
                'total_dias' => '25.00',
                'salario_mensual' => '5632.00',
                'monto' => '464.17',
                'cargo_suplencia' => 'Lecturador Cortador',
                'motivo' => NULL,
                'asignacion_cargo_id' => 103,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-04',
                'fecha_fin' => '2022-07-29',
                'total_dias' => '26.00',
                'salario_mensual' => '5632.00',
                'monto' => '482.73',
                'cargo_suplencia' => 'Lecturador Cortador',
                'motivo' => NULL,
                'asignacion_cargo_id' => 75,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-01',
                'fecha_fin' => '2022-07-22',
                'total_dias' => '22.00',
                'salario_mensual' => '11415.00',
                'monto' => '1261.33',
                'cargo_suplencia' => 'Jefe Red de Agua',
                'motivo' => NULL,
                'asignacion_cargo_id' => 178,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-18',
                'fecha_fin' => '2022-07-30',
                'total_dias' => '13.00',
                'salario_mensual' => '7221.00',
                'monto' => '383.07',
                'cargo_suplencia' => 'Cajero',
                'motivo' => NULL,
                'asignacion_cargo_id' => 231,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-01',
                'fecha_fin' => '2022-07-31',
                'total_dias' => '30.00',
                'salario_mensual' => '8547.00',
                'monto' => '1326.00',
                'cargo_suplencia' => 'Responsable de Cortes',
                'motivo' => NULL,
                'asignacion_cargo_id' => 172,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'mes' => 7,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-07-01',
                'fecha_fin' => '2022-07-31',
                'total_dias' => '30.00',
                'salario_mensual' => '7221.00',
                'monto' => '884.00',
                'cargo_suplencia' => 'Catastro de Usuarios',
                'motivo' => NULL,
                'asignacion_cargo_id' => 174,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-01',
                'fecha_fin' => '2022-08-31',
                'total_dias' => '30.00',
                'salario_mensual' => '17827.00',
                'monto' => '3693.00',
                'cargo_suplencia' => 'Gerente General',
                'motivo' => NULL,
                'asignacion_cargo_id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-01',
                'fecha_fin' => '2022-08-01',
                'total_dias' => '1.00',
                'salario_mensual' => '11415.00',
                'monto' => '57.33',
                'cargo_suplencia' => 'Jefe Captacion y Aduccion',
                'motivo' => NULL,
                'asignacion_cargo_id' => 212,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-01',
                'fecha_fin' => '2022-08-23',
                'total_dias' => '23.00',
                'salario_mensual' => '5075.00',
                'monto' => '255.30',
                'cargo_suplencia' => 'Operador Planta Potabilizadora',
                'motivo' => NULL,
                'asignacion_cargo_id' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-01',
                'fecha_fin' => '2022-08-08',
                'total_dias' => '8.00',
                'salario_mensual' => '14134.00',
                'monto' => '725.07',
                'cargo_suplencia' => 'Gerente Tecnico',
                'motivo' => NULL,
                'asignacion_cargo_id' => 59,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-01',
                'fecha_fin' => '2022-08-31',
                'total_dias' => '30.00',
                'salario_mensual' => '6337.00',
                'monto' => '705.00',
                'cargo_suplencia' => 'Inspector de Reclamos',
                'motivo' => NULL,
                'asignacion_cargo_id' => 161,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-01',
                'fecha_fin' => '2022-08-31',
                'total_dias' => '30.00',
                'salario_mensual' => '5632.00',
                'monto' => '557.00',
                'cargo_suplencia' => 'Lecturador Cortador',
                'motivo' => NULL,
                'asignacion_cargo_id' => 103,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-01',
                'fecha_fin' => '2022-08-09',
                'total_dias' => '9.00',
                'salario_mensual' => '11415.00',
                'monto' => '516.00',
                'cargo_suplencia' => 'Jefe Red de Agua',
                'motivo' => NULL,
                'asignacion_cargo_id' => 178,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-01',
                'fecha_fin' => '2022-08-02',
                'total_dias' => '2.00',
                'salario_mensual' => '7221.00',
                'monto' => '58.93',
                'cargo_suplencia' => 'Cajero',
                'motivo' => NULL,
                'asignacion_cargo_id' => 231,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-01',
                'fecha_fin' => '2022-08-31',
                'total_dias' => '30.00',
                'salario_mensual' => '8547.00',
                'monto' => '1326.00',
                'cargo_suplencia' => 'Responsable de Cortes',
                'motivo' => NULL,
                'asignacion_cargo_id' => 172,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-01',
                'fecha_fin' => '2022-08-31',
                'total_dias' => '30.00',
                'salario_mensual' => '7221.00',
                'monto' => '884.00',
                'cargo_suplencia' => 'Catastro de Usuarios',
                'motivo' => NULL,
                'asignacion_cargo_id' => 174,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-04',
                'fecha_fin' => '2022-08-24',
                'total_dias' => '21.00',
                'salario_mensual' => '11415.00',
                'monto' => '1204.00',
                'cargo_suplencia' => 'Jefe Planta Potabilizadora',
                'motivo' => NULL,
                'asignacion_cargo_id' => 206,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-02',
                'fecha_fin' => '2022-08-30',
                'total_dias' => '29.00',
                'salario_mensual' => '6337.00',
                'monto' => '1541.83',
                'cargo_suplencia' => 'Capataz Cancha Cancha',
                'motivo' => NULL,
                'asignacion_cargo_id' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-08',
                'fecha_fin' => '2022-08-30',
                'total_dias' => '23.00',
                'salario_mensual' => '6337.00',
                'monto' => '1222.83',
                'cargo_suplencia' => 'Capataz Cajamarca',
                'motivo' => NULL,
                'asignacion_cargo_id' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'fecha_inicio' => '2022-08-17',
                'fecha_fin' => '2022-08-30',
                'total_dias' => '14.00',
                'salario_mensual' => '7221.00',
                'monto' => '741.53',
                'cargo_suplencia' => 'Mecanico',
                'motivo' => NULL,
                'asignacion_cargo_id' => 138,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}