<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PlanillaOtroDescuentosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('planilla_otro_descuentos')->delete();
        
        \DB::table('planilla_otro_descuentos')->insert(array (
            0 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '176.58',
                'asignacion_cargo_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '176.58',
                'asignacion_cargo_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '157.45',
                'asignacion_cargo_id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '135.35',
                'asignacion_cargo_id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '135.35',
                'asignacion_cargo_id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '157.45',
                'asignacion_cargo_id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '176.58',
                'asignacion_cargo_id' => 15,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 17,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 34,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 35,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 37,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 38,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 41,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 43,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 45,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 46,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '176.58',
                'asignacion_cargo_id' => 50,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 52,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 53,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 54,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '176.58',
                'asignacion_cargo_id' => 57,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 60,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 61,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 62,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 63,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 65,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 66,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 68,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 69,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 70,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 71,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 74,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 75,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 76,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 77,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 79,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 80,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 82,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 83,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 84,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 86,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 89,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 90,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 91,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 92,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 93,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 95,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 96,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 99,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 103,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 104,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 105,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '176.58',
                'asignacion_cargo_id' => 118,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 119,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 120,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 121,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 122,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 123,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 126,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '135.35',
                'asignacion_cargo_id' => 130,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '135.35',
                'asignacion_cargo_id' => 133,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '135.35',
                'asignacion_cargo_id' => 136,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '135.35',
                'asignacion_cargo_id' => 137,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 138,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '157.45',
                'asignacion_cargo_id' => 141,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 146,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 147,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 150,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 151,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '135.35',
                'asignacion_cargo_id' => 152,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '135.35',
                'asignacion_cargo_id' => 153,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 154,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 155,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 156,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 157,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 158,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 159,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 161,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 162,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 164,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 166,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 168,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 170,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 171,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '135.35',
                'asignacion_cargo_id' => 172,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 173,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 174,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 175,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 176,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '176.58',
                'asignacion_cargo_id' => 178,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 179,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 181,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 182,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 183,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 184,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '157.45',
                'asignacion_cargo_id' => 187,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 188,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 189,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 191,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 192,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '176.58',
                'asignacion_cargo_id' => 193,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 194,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 195,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '157.45',
                'asignacion_cargo_id' => 197,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '135.35',
                'asignacion_cargo_id' => 199,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 200,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 201,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 202,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            120 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '176.58',
                'asignacion_cargo_id' => 203,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '157.45',
                'asignacion_cargo_id' => 204,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 205,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            123 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '176.58',
                'asignacion_cargo_id' => 206,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '157.45',
                'asignacion_cargo_id' => 207,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 208,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 209,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 210,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 213,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 214,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 215,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 216,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 217,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            133 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 218,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 219,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 220,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 221,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 222,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 224,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '157.45',
                'asignacion_cargo_id' => 225,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 226,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            141 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 227,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 228,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            143 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '157.45',
                'asignacion_cargo_id' => 229,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 230,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 231,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            146 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '99.58',
                'asignacion_cargo_id' => 232,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            147 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 233,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            148 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '108.87',
                'asignacion_cargo_id' => 234,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            149 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 237,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            150 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '94.03',
                'asignacion_cargo_id' => 238,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            151 => 
            array (
                'mes' => 8,
                'gestion' => 2022,
                'tipo_contrato' => 1,
                'descripcion' => 'APORTE POR JUBILACION MEDIO DIA DE HABER POR VICTOR PAREJA Y 15 POR FALLECIMIENTO DEL PAPA  DE PATRICIO CONDORI ',
                'factor_calculo' => '/30*0.5 + 15',
                'monto_od' => '120.62',
                'asignacion_cargo_id' => 239,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}